# 1.Setup

In [2]:
%pip install -q pandas numpy scikit-learn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
pd.set_option("display.max_columns",None)

# load dataset

In [14]:
df=sns.load_dataset("titanic")

In [15]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [16]:
df.columns.tolist()

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [17]:
# dropping alive column as it is redunant due to presense of survived columns
df=df.drop(columns=["alive"])

In [19]:
df.shape

(891, 14)

 3. Drop row with missing target( safe before train test split)

In [21]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alone            0
dtype: int64

In [25]:
target="survived"

missing_target_count=df[target].isna().sum()
missing_target_count

#drop the row that has missing target value
df=df.dropna(subset=[target])
df.shape

(891, 14)

4. Separate x(featues) and y(target)

In [29]:
x=df.drop(columns=[target]) 
y=df[target]

In [33]:
print(x.shape) 
print(y.shape)

(891, 13)
(891,)

In [34]:
x[:5]

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

In [35]:
y[:5]

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [41]:
print(y.value_counts())
print(y.value_counts(normalize=True).round(3))

survived
0    549
1    342
Name: count, dtype: int64
survived
0    0.616
1    0.384
Name: proportion, dtype: float64

**Train test and split**

In [47]:
X_train, X_test, y_train, y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [49]:
print("shape:")
print("X_train",X_train.shape)
print("X_test",X_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

shape:
X_train (712, 13)
X_test (179, 13)
y_train (712,)
y_test (179,)

In [51]:
X_train.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
692,3,male,NaN,0,0,56.4958,S,Third,man,True,NaN,Southampton,True
481,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,True
527,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,True
855,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,False
801,2,female,31.0,1,1,26.2500,S,Second,woman,False,NaN,Southampton,False

In [52]:
y_train.head()

692    1
481    0
527    0
855    1
801    1
Name: survived, dtype: int64

X_train, y_train --> Ml model learn the pattern

X_test, y_test --> Ml model Evalution

In [58]:
print("Target distribution of full data: ")
print(y.value_counts())

print("-"*50)
print("Target distributions on training data")
print(y_train.value_counts())

print("-"*50)
print("target distributions in percentage")
print(y_train.value_counts(normalize=True).round(3))


print("-"*50)
print("Target distributions on test data")
print(y_test.value_counts())

print("-"*50)
print("target distributions in percentage")
print(y_test.value_counts(normalize=True).round(3))
print("-"*50)

Target distribution of full data:
survived
0    549
1    342
Name: count, dtype: int64
--------------------------------------------------
Target distributions on training data
survived
0    439
1    273
Name: count, dtype: int64
--------------------------------------------------
target distributions in percentage
survived
0    0.617
1    0.383
Name: proportion, dtype: float64
--------------------------------------------------
Target distributions on test data
survived
0    110
1     69
Name: count, dtype: int64
--------------------------------------------------
target distributions in percentage
survived
0    0.615
1    0.385
Name: proportion, dtype: float64
--------------------------------------------------

6.Save Splits

In [59]:
train_df=X_train.copy()
train_df[target]=y_train.values

In [60]:
train_df.sample(6)

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone,survived
546,2,female,19.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,False,1
22,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,True,1
618,2,female,4.0,2,1,39.0000,S,Second,child,False,F,Southampton,False,1
418,2,male,30.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,True,0
430,1,male,28.0,0,0,26.5500,S,First,man,True,C,Southampton,True,1
774,2,female,54.0,1,3,23.0000,S,Second,woman,False,NaN,Southampton,False,1

In [61]:
test_df=X_test.copy()
test_df[target]=y_test.values

In [62]:
test_df.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone,survived
565,3,male,24.0,2,0,24.1500,S,Third,man,True,NaN,Southampton,False,0
160,3,male,44.0,0,1,16.1000,S,Third,man,True,NaN,Southampton,False,0
553,3,male,22.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,True,1
860,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,False,0
241,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,False,1

In [63]:
train_df.shape

(712, 14)

In [64]:
test_df.shape

(179, 14)

In [65]:
train_df.to_csv("titanic_train_raw.csv",index=False)
test_df.to_csv("titanic_test_raw.csv",index=False)