<b>Data Quality Check

In [2]:
#setup
import numpy as np
import pandas as pd
import seaborn as sns

pd.set_option("display.max_columns",None)#number of columns you see in print

<b>Load the Datasets

In [3]:
titanic=sns.load_dataset("titanic")

In [4]:
df=titanic

<b>3. Adding few columns for demonstarting data issue

In [5]:
df["PassengerId"]=np.arange(1,len(df)+1)
#constant columns
df["Constant_col"]=1

#create a dirty version of embaraked
df["Embarked_town_down"]=df["embark_town"].copy()

#select few random rows only no missing value
sample_idx=df["Embarked_town_down"].dropna().sample(6,random_state=42).index
#apply simple dirty transformation
df.loc[sample_idx[0:2],"Embarked_town_down"]=df.loc[sample_idx[0:2],"Embarked_town_down"].str.upper()
df.loc[sample_idx[2:4],"Embarked_town_down"]=df.loc[sample_idx[2:4],"Embarked_town_down"].str.strip().apply(lambda x:f" {x} ")
df.loc[sample_idx[4:6],"Embarked_town_down"]="unknown"

In [6]:
df.shape

(891, 18)

<b>3. Data Quality Checklist<b/><br>
1. Basic dataset overview<br>
2. Missing Values summary<br>
3. Duplicates<br>
4. Data type Validation<br>
5. Constant and quasi constant columns<br>
6. Id like columns<br>
7. String inconsistencies<br>
8. High null columns<br>
9. High Zero columns <br>

4.1 Basic dataset overview

In [7]:
df.shape

(891, 18)

In [8]:
df.dtypes

survived                 int64
pclass                   int64
sex                        str
age                    float64
sibsp                    int64
parch                    int64
fare                   float64
embarked                   str
class                 category
who                        str
adult_male                bool
deck                  category
embark_town                str
alive                      str
alone                     bool
PassengerId              int64
Constant_col             int64
Embarked_town_down         str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survived            891 non-null    int64
 1   pclass              891 non-null    int64
 2   sex                 891 non-null    str
 3   age                 714 non-null    float64
 4   sibsp               891 non-null    int64
 5   parch               891 non-null    int64
 6   fare                891 non-null    float64
 7   embarked            889 non-null    str
 8   class               891 non-null    category
 9   who                 891 non-null    str
 10  adult_male          891 non-null    bool
 11  deck                203 non-null    category
 12  embark_town         889 non-null    str
 13  alive               891 non-null    str
 14  alone               891 non-null    bool
 15  PassengerId         891 non-null    int64
 16  Constant_col        891 non-null    int64
 17  Embarked_town_down  889 non-null    str
dtypes: bool(2), category(2), float64(2), int64(6), str(6)
memory usage: 130.5 KB

In [10]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'PassengerId', 'Constant_col', 'Embarked_town_down'],
      dtype='str')

In [11]:
df.nunique()

survived                2
pclass                  3
sex                     2
age                    88
sibsp                   7
parch                   7
fare                  248
embarked                3
class                   3
who                     3
adult_male              2
deck                    7
embark_town             3
alive                   2
alone                   2
PassengerId           891
Constant_col            1
Embarked_town_down      7
dtype: int64

In [12]:
df.describe(
    
)

,survived,pclass,age,sibsp,parch,fare,PassengerId,Constant_col
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.0
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,446.000000,1.0
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,257.353842,0.0
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000,1.0
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,223.500000,1.0
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,446.000000,1.0
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,668.500000,1.0
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,891.000000,1.0

2.missing value summary

In [13]:
missing_count=df.isna().sum().sort_values(ascending=False)
missing_percent=(df.isna().mean()*100).sort_values(ascending=False)

missing_summary=pd.DataFrame({
    "missing_count":missing_count,
    "missing_percent":missing_percent
    
})

missing_summary
# print(df.isna().mean())

                    missing_count  missing_percent
deck                          688        77.216611
age                           177        19.865320
Embarked_town_down              2         0.224467
embarked                        2         0.224467
embark_town                     2         0.224467
survived                        0         0.000000
pclass                          0         0.000000
parch                           0         0.000000
sibsp                           0         0.000000
sex                             0         0.000000
who                             0         0.000000
class                           0         0.000000
fare                            0         0.000000
adult_male                      0         0.000000
alive                           0         0.000000
alone                           0         0.000000
PassengerId                     0         0.000000
Constant_col                    0         0.000000

In [14]:
df.isnull().count()

survived              891
pclass                891
sex                   891
age                   891
sibsp                 891
parch                 891
fare                  891
embarked              891
class                 891
who                   891
adult_male            891
deck                  891
embark_town           891
alive                 891
alone                 891
PassengerId           891
Constant_col          891
Embarked_town_down    891
dtype: int64

4.3 checking for duplicates

In [15]:
duplicates_mask=df.duplicated()
num_duplicates=duplicates_mask.sum()
num_duplicates

np.int64(0)

In [16]:
duplicates_mask=df.duplicated()
print(duplicates_mask)

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [17]:
df_no_duplicates=df.drop_duplicates()
df_no_duplicates

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,PassengerId,Constant_col,Embarked_town_down
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,887,1,Southampton
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,888,1,Southampton
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,889,1,Southampton
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,890,1,Cherbourg
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,891,1,Queenstown

4.4 Data type Validation

In [18]:
expected_types={
    "survived":"int64",
    "pclass":"int64",
    "sex":"category",
    "age":"float",
    "fare":"float64"
}
# print(expected_types)
for col,expected in expected_types.items():
    if col  in df.columns:
        actual=df[col].dtypes
        print(f"{col}: actual={actual},expected:{expected}")

survived: actual=int64,expected:int64
pclass: actual=int64,expected:int64
sex: actual=str,expected:category
age: actual=float64,expected:float
fare: actual=float64,expected:float64

In [19]:
#df["plcass"]=df["pclass"].astype("int64")

4.5 Constant and quasi constant columns

In [20]:
df.nunique()

survived                2
pclass                  3
sex                     2
age                    88
sibsp                   7
parch                   7
fare                  248
embarked                3
class                   3
who                     3
adult_male              2
deck                    7
embark_town             3
alive                   2
alone                   2
PassengerId           891
Constant_col            1
Embarked_town_down      7
dtype: int64

In [21]:
n_rows=len(df)
nunique=df.nunique()

constant_cols=nunique[nunique==1].index.to_list()
# print(constant_cols) 

#quasi constant column
#95 % percent of value is common
quasi_constant_cols=[]
for col in df.columns:
    top_freq=df[col].value_counts(normalize=True, dropna=False).values[0]
    if top_freq>0.75 and col not in constant_cols:
        quasi_constant_cols.append(col)
        
        
        
print("Quasi constant columns (top value more than 90 % ):\n ",quasi_constant_cols)

Quasi constant columns (top value more than 90 % ):
  ['parch', 'deck']

In [22]:
df["pclass"].value_counts().values

array([491, 216, 184])

Id like columns

columns wherer number of unique value is near to number of column

In [23]:
n_rows=len(df)

id_like_cols=[]

for col in df.columns:
    if df[col].nunique(dropna=False)==n_rows:
        id_like_cols.append(col)
        
        
print("Id like colums: ",id_like_cols)

Id like colums:  ['PassengerId']

**String Consistency**

In [29]:
object_cols=df.select_dtypes(include=["object"]).columns.to_list()  
print("Object or category basecd columns:",object_cols)

#simple clean and convert them into lower case

df["embark_town_clean"]=(df["Embarked_town_down"]
.astype(str)
.str.strip()
.str.lower()
.replace("unknown",np.nan))

Object or category basecd columns: ['sex', 'embarked', 'who', 'embark_town', 'alive', 'Embarked_town_down']

C:\Users\kaush\AppData\Local\Temp\ipykernel_20604\497512549.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols=df.select_dtypes(include=["object"]).columns.to_list()

In [30]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [31]:
df.iloc[435]

survived                        1
pclass                          1
sex                        female
age                          14.0
sibsp                           1
parch                           2
fare                        120.0
embarked                        S
class                       First
who                         child
adult_male                  False
deck                            B
embark_town           Southampton
alive                         yes
alone                       False
PassengerId                   436
Constant_col                    1
Embarked_town_down    SOUTHAMPTON
embark_town_clean     southampton
Name: 435, dtype: object

**High Null columns**

In [32]:
high_null_threshold=0.4
high_null_cols=missing_summary[missing_summary["missing_percent"]>=high_null_threshold*100]
print("Columns with high missing percentage:")
print(high_null_cols)

Columns with high missing percentage:
      missing_count  missing_percent
deck            688        77.216611

4.9 High zero columns (numeric)

In [42]:
numeric_cols=df.select_dtypes(include=[np.number]).columns.to_list() 
zero_share={}
for col in numeric_cols:
    zero_share[col]=(df[col]==0).mean()
    
zero_share_series=pd.Series(zero_share).sort_values(ascending=False)

print(zero_share_series )
print("--"*30)

high_zero_threshold=0.7
high_zero_cols=zero_share_series[zero_share_series >=high_zero_threshold]
print("Numeric columns with many zeros:",high_zero_cols)

parch           0.760943
sibsp           0.682379
survived        0.616162
fare            0.016835
age             0.000000
pclass          0.000000
PassengerId     0.000000
Constant_col    0.000000
dtype: float64
------------------------------------------------------------
Numeric columns with many zeros: parch    0.760943
dtype: float64