In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("placement.csv")

In [4]:
df.head(
    
)

   Unnamed: 0  cgpa   iq  placement
0           0   6.8  123          1
1           1   5.9  106          0
2           2   5.3  121          0
3           3   7.4  132          1
4           4   5.8  142          0

In [11]:
df.iloc[:,:1]

    Unnamed: 0
0            0
1            1
2            2
3            3
4            4
..         ...
95          95
96          96
97          97
98          98
99          99

[100 rows x 1 columns]