In [1]:
%pip install plotly

Requirement already satisfied: plotly in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv\lib\site-packages (6.8.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv\lib\site-packages (from plotly) (2.22.1)
Requirement already satisfied: packaging in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv\lib\site-packages (from plotly) (26.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
 
np.random.seed(23)
mu_vec1=np.array([0,0,0])
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])
 
class1_sample=np.random.multivariate_normal(mu_vec1,cov_mat1,20)
 
df=pd.DataFrame(class1_sample,columns=["feature1","feature2","feature3"])
df['target']=1


mu_vec2=np.array([1,1,1])
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]])
 
class2_sample=np.random.multivariate_normal(mu_vec2,cov_mat2,20)
 
df1=pd.DataFrame(class1_sample,columns=["feature1","feature2","feature3"])
df1['target']=0

# df=df.a(df1,ignore_index=True)
df=pd.concat([df,df1],ignore_index=True)
 
df=df.sample(40)

In [3]:
df

    feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.420623  0.411620 -0.071324       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
29  1.267248  0.173634 -1.223255       0
31  1.968435 -0.547788 -0.679418       0
4   0.322272  0.060343 -1.043450       1
32 -2.506230  0.146960  0.606195       0
33 -0.022539  0.013422  0.935945       0
36 -0.420844 -0.551989 -0.121098       0
18 -0.331617 -1.632386  0.619114       1
0   0.666988  0.025813 -0.777619       1
5  -1.009942  0.441736  1.128877       1
39 -0.992574 -0.161346  1.192404       0
22 -0.367548 -1.137460 -1.322148       0
8   0.241106 -0.952510 -0.136267       1
15 -0.045438  1.040886 -0.094035       1
19 -0.992574 -0.161346  1.192404       1
30  1.415320  0.457711  0.728876       0
25 -1.009942  0.441736  1.128877       0
21  0.948634  0.701672 -1.051082       0
37  0.190141  0.512137  0.131538       0
16 -0.420844 -0.551989 -0.121098       1
38 -0.331617 -1.632386  0.619114       0
27  1.045371  0.538162  0.812119       0
26 -1.838068 -0.938769 -0.201841       0
23  1.772258 -0.347459  0.670140       0
1   0.948634  0.701672 -1.051082       1
10  1.415320  0.457711  0.728876       1
20  0.666988  0.025813 -0.777619       0
28  0.241106 -0.952510 -0.136267       0
24  0.322272  0.060343 -1.043450       0
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
17  0.190141  0.512137  0.131538       1
13 -0.022539  0.013422  0.935945       1
9   1.267248  0.173634 -1.223255       1
35 -0.045438  1.040886 -0.094035       0
3   1.772258 -0.347459  0.670140       1

In [5]:
import plotly.express as px
fig=px.scatter_3d(df,x=df['feature1'],y=df['feature2'],z=df['feature3'],color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,line=dict(width=2,color="DarkSlateGrey")),selector=dict(mode='marker'))
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df.iloc[:,0:3]=scaler.fit_transform(df.iloc[:,0:3])

In [13]:
covariance_matrix=np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('covariance_matrix'  , covariance_matrix,"\n")

covariance_matrix [[ 1.02564103  0.19874576 -0.28147286]
 [ 0.19874576  1.02564103  0.10675198]
 [-0.28147286  0.10675198  1.02564103]]

In [15]:
#find out the eigen values and eigen vectors
eigen_value,eigen_vectors=np.linalg.eig(covariance_matrix)

In [16]:
eigen_value

array([0.6256614 , 1.32630385, 1.12495783])

In [17]:
eigen_vectors

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ],
       [-0.58686326, -0.60066414,  0.54294945]])

In [18]:
pc=eigen_vectors[0:2]
pc

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ]])

In [20]:
transformed_df=np.dot(df.iloc[:,0:3],pc.T)
new_df=pd.DataFrame(transformed_df,columns=["pc1","pc2"])
new_df['target']=df['target'].values
new_df

         pc1       pc2  target
0  -1.078773 -2.044435       1
1   0.376154  0.249784       0
2   0.376154  0.249784       1
3  -1.682116 -0.124367       1
4   1.888923 -0.404657       1
5  -0.559160 -0.693634       0
6  -1.682116 -0.124367       0
7  -0.107685 -0.957342       1
8   1.888923 -0.404657       0
9   0.348857  0.949148       0
10 -0.211406 -0.564757       0
11 -1.346330 -0.201641       1
12 -0.304909 -0.545559       1
13  1.427756  0.906913       1
14  0.758641  0.729374       0
15 -1.078773 -2.044435       0
16 -1.042675 -0.464117       1
17  1.341405  0.288784       1
18  0.758641  0.729374       1
19 -0.026152  1.533499       0
20  1.427756  0.906913       0
21  0.238477 -0.429512       0
22  0.653167  0.405505       0
23 -0.211406 -0.564757       1
24 -1.346330 -0.201641       0
25  0.291023  1.495777       0
26  0.170583 -1.417818       0
27 -1.135779  1.289053       0
28  0.238477 -0.429512       1
29 -0.026152  1.533499       1
30 -0.304909 -0.545559       0
31 -1.042675 -0.464117       0
32 -0.107685 -0.957342       0
33  0.291023  1.495777       1
34  0.170583 -1.417818       1
35  0.653167  0.405505       1
36  0.348857  0.949148       1
37 -0.559160 -0.693634       1
38  1.341405  0.288784       0
39 -1.135779  1.289053       1